/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visualui;

//import java.awt.*;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
//import javax.swing.SwingUtilities;

//import java.awt.event.*;
//import javax.swing.*;
//import java.awt.Component;
//import javax.swing.Box;

/**
 *
 * @author moren398
 */
public class ListUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    //added
    boolean a = true;
    
    public ListUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        topHeader = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        listViewPanel = new javax.swing.JPanel();
        listViewLabel = new javax.swing.JLabel();
        listViewPane = new javax.swing.JScrollPane();
        listViewList = new javax.swing.JList<>();

        jPopupMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setInheritsPopupMenu(true);
        jPopupMenu1.setMaximumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setPopupSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setRequestFocusEnabled(false);
        jPopupMenu1.getAccessibleContext().setAccessibleDescription("");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setMinimumSize(new java.awt.Dimension(400, 50));
        jMenuItem1.setPreferredSize(new java.awt.Dimension(400, 50));
        jMenuItem1.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setMaximumSize(new java.awt.Dimension(400, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(400, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(400, 50));
        jButton2.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainFrame");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 800));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {80};
        layout.rowHeights = new int[] {50};
        layout.columnWeights = new double[] {0.2, 0.2};
        layout.rowWeights = new double[] {0.5, 0.5};
        getContentPane().setLayout(layout);

        topHeader.setBackground(new java.awt.Color(255, 255, 255));
        topHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        topHeader.setForeground(new java.awt.Color(255, 255, 255));
        topHeader.setAlignmentX(0.0F);
        topHeader.setAlignmentY(0.0F);
        topHeader.setMaximumSize(new java.awt.Dimension(396, 50));
        topHeader.setMinimumSize(new java.awt.Dimension(396, 50));
        topHeader.setPreferredSize(new java.awt.Dimension(396, 50));
        topHeader.setLayout(new java.awt.GridBagLayout());

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 255));
        homeButton.setText("Signal Spotter");
        homeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        homeButton.setBorderPainted(false);
        homeButton.setMaximumSize(new java.awt.Dimension(396, 44));
        homeButton.setMinimumSize(new java.awt.Dimension(396, 44));
        homeButton.setPreferredSize(new java.awt.Dimension(396, 44));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        topHeader.add(homeButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.125;
        getContentPane().add(topHeader, gridBagConstraints);
        topHeader.getAccessibleContext().setAccessibleName("");
        topHeader.getAccessibleContext().setAccessibleDescription("");

        listViewPanel.setBackground(new java.awt.Color(153, 255, 255));
        listViewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        listViewPanel.setForeground(new java.awt.Color(255, 255, 0));
        listViewPanel.setAlignmentX(0.0F);
        listViewPanel.setAlignmentY(2.0F);
        listViewPanel.setMaximumSize(new java.awt.Dimension(400, 750));
        listViewPanel.setMinimumSize(new java.awt.Dimension(400, 750));
        listViewPanel.setPreferredSize(new java.awt.Dimension(400, 750));
        listViewPanel.setLayout(new java.awt.BorderLayout(10, 0));

        listViewLabel.setBackground(new java.awt.Color(0, 0, 255));
        listViewLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        listViewLabel.setForeground(new java.awt.Color(255, 255, 255));
        listViewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listViewLabel.setText("List View");
        listViewLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listViewLabel.setMaximumSize(new java.awt.Dimension(100, 50));
        listViewLabel.setMinimumSize(new java.awt.Dimension(100, 50));
        listViewLabel.setOpaque(true);
        listViewLabel.setPreferredSize(new java.awt.Dimension(100, 50));
        listViewPanel.add(listViewLabel, java.awt.BorderLayout.PAGE_START);

        listViewPane.setBackground(new java.awt.Color(255, 255, 255));
        listViewPane.setBorder(null);
        listViewPane.setForeground(new java.awt.Color(0, 0, 255));
        listViewPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        listViewPane.setColumnHeaderView(null);
        listViewPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listViewPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listViewPane.setHorizontalScrollBar(null);
        listViewPane.setMaximumSize(new java.awt.Dimension(400, 695));
        listViewPane.setMinimumSize(new java.awt.Dimension(400, 695));
        listViewPane.setPreferredSize(new java.awt.Dimension(400, 695));
        listViewPane.setRowHeaderView(null);
        listViewPane.setViewportView(listViewList);

        listViewList.setBackground(new java.awt.Color(255, 255, 255));
        listViewList.setBorder(null);
        listViewList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        listViewList.setForeground(new java.awt.Color(0, 0, 255));
        listViewList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listViewList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listViewList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listViewList.setMaximumSize(new java.awt.Dimension(396, 695));
        listViewList.setMinimumSize(new java.awt.Dimension(396, 695));
        listViewList.setPreferredSize(new java.awt.Dimension(396, 695));
        listViewList.setSelectionBackground(new java.awt.Color(0, 102, 255));
        listViewList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listViewList.setVisibleRowCount(25);
        listViewPane.setViewportView(listViewList);

        listViewPanel.add(listViewPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(listViewPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //function for when menu is clicked
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(Color.red);
            h2.setBackground(Color.pink);
        }else{
            h2.setBackground(Color.red);
            h1.setBackground(Color.pink);
        }
    }
    
    //function for hiding/showing the menu
    public void hideshow(JPanel menushowhide, boolean dashboard){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(10, 10));
        }else{
            menushowhide.setPreferredSize(new Dimension(396, 250));
        }
    }
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //return to home page when header button clicked
        HomeUI home = new HomeUI();
        home.setVisible(a);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel listViewLabel;
    private javax.swing.JList<String> listViewList;
    private javax.swing.JScrollPane listViewPane;
    public javax.swing.JPanel listViewPanel;
    public javax.swing.JPanel topHeader;
    // End of variables declaration//GEN-END:variables
}
