/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visualui;

//import java.awt.*;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
//import javax.swing.SwingUtilities;

//import java.awt.event.*;
//import javax.swing.*;
//import java.awt.Component;
//import javax.swing.Box;

/**
 *
 * @author moren398
 */
public class ReportUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    //added
    boolean a = true;
    
    public ReportUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        qualityButtons = new javax.swing.ButtonGroup();
        topHeader = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        rSignalLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        locationLabel = new javax.swing.JLabel();
        pickLocationBox = new javax.swing.JComboBox<>();
        qualityLabel = new javax.swing.JLabel();
        goodSignal = new javax.swing.JRadioButton();
        okaySignal = new javax.swing.JRadioButton();
        badSignal = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        jPopupMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setInheritsPopupMenu(true);
        jPopupMenu1.setMaximumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setPopupSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setRequestFocusEnabled(false);
        jPopupMenu1.getAccessibleContext().setAccessibleDescription("");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setMinimumSize(new java.awt.Dimension(400, 50));
        jMenuItem1.setPreferredSize(new java.awt.Dimension(400, 50));
        jMenuItem1.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setMaximumSize(new java.awt.Dimension(400, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(400, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(400, 50));
        jButton2.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainFrame");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 800));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {80};
        layout.rowHeights = new int[] {50};
        layout.columnWeights = new double[] {0.2, 0.2};
        layout.rowWeights = new double[] {0.5, 0.5};
        getContentPane().setLayout(layout);

        topHeader.setBackground(new java.awt.Color(255, 255, 255));
        topHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        topHeader.setForeground(new java.awt.Color(255, 255, 255));
        topHeader.setAlignmentX(0.0F);
        topHeader.setAlignmentY(0.0F);
        topHeader.setMaximumSize(new java.awt.Dimension(400, 50));
        topHeader.setMinimumSize(new java.awt.Dimension(400, 50));
        topHeader.setPreferredSize(new java.awt.Dimension(400, 50));
        topHeader.setLayout(new java.awt.GridBagLayout());

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 255));
        homeButton.setText("Signal Spotter");
        homeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        homeButton.setBorderPainted(false);
        homeButton.setMaximumSize(new java.awt.Dimension(396, 44));
        homeButton.setMinimumSize(new java.awt.Dimension(396, 44));
        homeButton.setPreferredSize(new java.awt.Dimension(396, 44));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        topHeader.add(homeButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.125;
        getContentPane().add(topHeader, gridBagConstraints);
        topHeader.getAccessibleContext().setAccessibleName("");
        topHeader.getAccessibleContext().setAccessibleDescription("");

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        reportPanel.setForeground(new java.awt.Color(255, 255, 0));
        reportPanel.setAlignmentX(0.0F);
        reportPanel.setAlignmentY(2.0F);
        reportPanel.setMaximumSize(new java.awt.Dimension(400, 750));
        reportPanel.setMinimumSize(new java.awt.Dimension(400, 750));
        reportPanel.setPreferredSize(new java.awt.Dimension(400, 750));

        rSignalLabel.setBackground(new java.awt.Color(0, 0, 255));
        rSignalLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rSignalLabel.setForeground(new java.awt.Color(255, 255, 255));
        rSignalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSignalLabel.setLabelFor(rSignalLabel);
        rSignalLabel.setText("Report Signal");
        rSignalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSignalLabel.setInheritsPopupMenu(false);
        rSignalLabel.setMaximumSize(new java.awt.Dimension(396, 50));
        rSignalLabel.setMinimumSize(new java.awt.Dimension(396, 50));
        rSignalLabel.setOpaque(true);
        rSignalLabel.setPreferredSize(new java.awt.Dimension(396, 50));

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 255));
        emailLabel.setLabelFor(emailField);
        emailLabel.setText("Enter Email:");

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 255));
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setText("Email");
        emailField.setToolTipText("");
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        emailField.setCaretColor(new java.awt.Color(0, 0, 255));
        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailField.setMaximumSize(new java.awt.Dimension(200, 50));
        emailField.setMinimumSize(new java.awt.Dimension(200, 50));
        emailField.setOpaque(true);
        emailField.setPreferredSize(new java.awt.Dimension(200, 50));
        emailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFieldMouseClicked(evt);
            }
        });

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 255));
        passwordLabel.setLabelFor(passwordField);
        passwordLabel.setText("Enter Password:");

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 255));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("Password");
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        passwordField.setCaretColor(new java.awt.Color(0, 0, 255));
        passwordField.setMaximumSize(new java.awt.Dimension(200, 50));
        passwordField.setMinimumSize(new java.awt.Dimension(200, 50));
        passwordField.setPreferredSize(new java.awt.Dimension(200, 50));
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });

        locationLabel.setBackground(new java.awt.Color(255, 255, 255));
        locationLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(0, 0, 255));
        locationLabel.setLabelFor(pickLocationBox);
        locationLabel.setText("Choose Location:");

        pickLocationBox.setBackground(new java.awt.Color(255, 255, 255));
        pickLocationBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pickLocationBox.setForeground(new java.awt.Color(0, 0, 255));
        pickLocationBox.setMaximumRowCount(16);
        pickLocationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic Hall", "Arts Building", "Clarke Field House", "Craven Hall", "Kellogg Library", "Markstein Hall", "Science Hall 1", "Science Hall 2", "SBSB", "Sports Center", "SHCSB", "University Commons", "University Hall", "USU", "UVA", "Veteran's Center" }));
        pickLocationBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        pickLocationBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pickLocationBox.setMaximumSize(new java.awt.Dimension(200, 50));
        pickLocationBox.setMinimumSize(new java.awt.Dimension(200, 50));
        pickLocationBox.setName(""); // NOI18N
        pickLocationBox.setOpaque(true);
        pickLocationBox.setPreferredSize(new java.awt.Dimension(200, 50));
        pickLocationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickLocationBoxActionPerformed(evt);
            }
        });

        qualityLabel.setBackground(new java.awt.Color(255, 255, 255));
        qualityLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        qualityLabel.setForeground(new java.awt.Color(0, 0, 255));
        qualityLabel.setLabelFor(goodSignal);
        qualityLabel.setText("Signal Quality:");

        goodSignal.setBackground(new java.awt.Color(255, 255, 255));
        qualityButtons.add(goodSignal);
        goodSignal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        goodSignal.setForeground(new java.awt.Color(0, 0, 255));
        goodSignal.setSelected(true);
        goodSignal.setText("Good");
        goodSignal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        goodSignal.setBorderPainted(true);
        goodSignal.setMaximumSize(new java.awt.Dimension(200, 50));
        goodSignal.setMinimumSize(new java.awt.Dimension(200, 50));
        goodSignal.setOpaque(true);
        goodSignal.setPreferredSize(new java.awt.Dimension(200, 50));
        goodSignal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goodSignalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goodSignalMousePressed(evt);
            }
        });

        okaySignal.setBackground(new java.awt.Color(255, 255, 255));
        qualityButtons.add(okaySignal);
        okaySignal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        okaySignal.setForeground(new java.awt.Color(0, 0, 255));
        okaySignal.setText("Okay");
        okaySignal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        okaySignal.setBorderPainted(true);
        okaySignal.setMaximumSize(new java.awt.Dimension(200, 50));
        okaySignal.setMinimumSize(new java.awt.Dimension(200, 50));
        okaySignal.setOpaque(true);
        okaySignal.setPreferredSize(new java.awt.Dimension(200, 50));
        okaySignal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okaySignalMouseClicked(evt);
            }
        });

        badSignal.setBackground(new java.awt.Color(255, 255, 255));
        qualityButtons.add(badSignal);
        badSignal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        badSignal.setForeground(new java.awt.Color(0, 0, 255));
        badSignal.setText("Bad");
        badSignal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        badSignal.setBorderPainted(true);
        badSignal.setMaximumSize(new java.awt.Dimension(200, 50));
        badSignal.setMinimumSize(new java.awt.Dimension(200, 50));
        badSignal.setOpaque(true);
        badSignal.setPreferredSize(new java.awt.Dimension(200, 50));
        badSignal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badSignalMouseClicked(evt);
            }
        });
        badSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badSignalActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(0, 0, 255));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.setMaximumSize(new java.awt.Dimension(200, 50));
        submitButton.setMinimumSize(new java.awt.Dimension(200, 50));
        submitButton.setOpaque(true);
        submitButton.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSignalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goodSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pickLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okaySignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(badSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(emailLabel))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(passwordLabel))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(locationLabel))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(qualityLabel))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addComponent(rSignalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(emailLabel)
                .addGap(18, 18, 18)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(passwordLabel)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(locationLabel)
                .addGap(18, 18, 18)
                .addComponent(pickLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(qualityLabel)
                .addGap(18, 18, 18)
                .addComponent(goodSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okaySignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(badSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(reportPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //function for when menu is clicked
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(Color.red);
            h2.setBackground(Color.pink);
        }else{
            h2.setBackground(Color.red);
            h1.setBackground(Color.pink);
        }
    }
    
    //function for hiding/showing the menu
    public void hideshow(JPanel menushowhide, boolean dashboard){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(10, 10));
        }else{
            menushowhide.setPreferredSize(new Dimension(396, 250));
        }
    }
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //return to home page when header button clicked
        HomeUI home = new HomeUI();
        home.setVisible(a);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void pickLocationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickLocationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickLocationBoxActionPerformed

    private void badSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badSignalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badSignalActionPerformed

    private void emailFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseClicked
        // TODO add your handling code here:
        emailField.setText("");
    }//GEN-LAST:event_emailFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void goodSignalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goodSignalMousePressed
        //set button green when clicked
        goodSignal.setBackground(Color.green);
        okaySignal.setBackground(Color.white);
        badSignal.setBackground(Color.white);
    }//GEN-LAST:event_goodSignalMousePressed

    private void goodSignalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goodSignalMouseClicked
        // TODO add your handling code here:
        //goodSignal.setBackground(Color.green);
    }//GEN-LAST:event_goodSignalMouseClicked

    private void okaySignalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okaySignalMouseClicked
        //set button yellow when clicked
        goodSignal.setBackground(Color.white);
        okaySignal.setBackground(Color.yellow);
        badSignal.setBackground(Color.white);
    }//GEN-LAST:event_okaySignalMouseClicked

    private void badSignalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badSignalMouseClicked
        //set button red when clicked
        goodSignal.setBackground(Color.white);
        okaySignal.setBackground(Color.white);
        badSignal.setBackground(Color.red);
    }//GEN-LAST:event_badSignalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton badSignal;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton goodSignal;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JRadioButton okaySignal;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> pickLocationBox;
    private javax.swing.ButtonGroup qualityButtons;
    private javax.swing.JLabel qualityLabel;
    private javax.swing.JLabel rSignalLabel;
    public javax.swing.JPanel reportPanel;
    private javax.swing.JButton submitButton;
    public javax.swing.JPanel topHeader;
    // End of variables declaration//GEN-END:variables
}
