/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visualui;

//import java.awt.*;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
//import javax.swing.SwingUtilities;

//import java.awt.event.*;
//import javax.swing.*;
//import java.awt.Component;
//import javax.swing.Box;

/**
 *
 * @author moren398
 */
public class TrendsUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    //added
    boolean a = true;
    
    public TrendsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        topHeader = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        trendsPanel = new javax.swing.JPanel();
        trendsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPopupMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setInheritsPopupMenu(true);
        jPopupMenu1.setMaximumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setPopupSize(new java.awt.Dimension(400, 250));
        jPopupMenu1.setRequestFocusEnabled(false);
        jPopupMenu1.getAccessibleContext().setAccessibleDescription("");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setMinimumSize(new java.awt.Dimension(400, 50));
        jMenuItem1.setPreferredSize(new java.awt.Dimension(400, 50));
        jMenuItem1.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setMaximumSize(new java.awt.Dimension(400, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(400, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(400, 50));
        jButton2.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainFrame");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 800));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {80};
        layout.rowHeights = new int[] {50};
        layout.columnWeights = new double[] {0.2, 0.2};
        layout.rowWeights = new double[] {0.5, 0.5};
        getContentPane().setLayout(layout);

        topHeader.setBackground(new java.awt.Color(255, 255, 255));
        topHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        topHeader.setForeground(new java.awt.Color(255, 255, 255));
        topHeader.setAlignmentX(0.0F);
        topHeader.setAlignmentY(0.0F);
        topHeader.setMaximumSize(new java.awt.Dimension(396, 50));
        topHeader.setMinimumSize(new java.awt.Dimension(396, 50));
        topHeader.setPreferredSize(new java.awt.Dimension(396, 50));
        topHeader.setLayout(new java.awt.GridBagLayout());

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 255));
        homeButton.setText("Signal Spotter");
        homeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        homeButton.setBorderPainted(false);
        homeButton.setMaximumSize(new java.awt.Dimension(396, 44));
        homeButton.setMinimumSize(new java.awt.Dimension(396, 44));
        homeButton.setPreferredSize(new java.awt.Dimension(396, 44));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        topHeader.add(homeButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.125;
        getContentPane().add(topHeader, gridBagConstraints);
        topHeader.getAccessibleContext().setAccessibleName("");
        topHeader.getAccessibleContext().setAccessibleDescription("");

        trendsPanel.setBackground(new java.awt.Color(153, 255, 255));
        trendsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        trendsPanel.setForeground(new java.awt.Color(255, 255, 0));
        trendsPanel.setAlignmentX(0.0F);
        trendsPanel.setAlignmentY(2.0F);
        trendsPanel.setMaximumSize(new java.awt.Dimension(400, 750));
        trendsPanel.setMinimumSize(new java.awt.Dimension(400, 750));
        trendsPanel.setPreferredSize(new java.awt.Dimension(400, 750));
        trendsPanel.setLayout(new java.awt.BorderLayout(10, 0));

        trendsLabel.setBackground(new java.awt.Color(0, 0, 255));
        trendsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        trendsLabel.setForeground(new java.awt.Color(255, 255, 255));
        trendsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trendsLabel.setText("Wifi Strength Trends");
        trendsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        trendsLabel.setMaximumSize(new java.awt.Dimension(100, 50));
        trendsLabel.setMinimumSize(new java.awt.Dimension(100, 50));
        trendsLabel.setOpaque(true);
        trendsLabel.setPreferredSize(new java.awt.Dimension(100, 50));
        trendsPanel.add(trendsLabel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 255));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setHorizontalScrollBar(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Location", "Best Days", "Best Times"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 255));
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        trendsPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(trendsPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //function for when menu is clicked
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(Color.red);
            h2.setBackground(Color.pink);
        }else{
            h2.setBackground(Color.red);
            h1.setBackground(Color.pink);
        }
    }
    
    //function for hiding/showing the menu
    public void hideshow(JPanel menushowhide, boolean dashboard){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(10, 10));
        }else{
            menushowhide.setPreferredSize(new Dimension(396, 250));
        }
    }
    
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //return to home page when header button clicked
        HomeUI home = new HomeUI();
        home.setVisible(a);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrendsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrendsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrendsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrendsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrendsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JPanel topHeader;
    private javax.swing.JLabel trendsLabel;
    public javax.swing.JPanel trendsPanel;
    // End of variables declaration//GEN-END:variables
}
